version: '3'
services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/html
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: intern_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1111
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: 1111
    ports:
      - 8080:80

  nginx:
    image: nginx:latest
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./:/var/www/html
    ports:
      - 80:80
    restart: always
